
name: build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[ci skip]')
    steps:
      - name: checkout repository
        uses: actions/checkout@v4.1.1
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2.1.1
      - name: setup jdk 17
        uses: actions/setup-java@v4.1.0
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: |
          ./gradlew build

  run_tests:
    uses: constellation-mc/actions/.github/workflows/mc-tests.yml@main
    with:
      java: 17
      client_task: runClient
      server_task: runServer

  packages:
    needs:
      - build
      - run_tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4.1.1
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2.1.1
      - name: setup jdk 17
        uses: actions/setup-java@v4.1.0
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew publish